os: Visual Studio 2015
shallow_clone: true
install:
build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86'
  - build.bat
  - move build dependencies
  - 7z a dependencies.zip dependencies\
artifacts:
  - path: dependencies.zip
deploy:
  - provider: GitHub
    release: master-builds
    description: 'Automatic builds from the master branch'
    auth_token:
      secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
    artifact: /.*zip/
    draft: false
    prerelease: true
    on:
      branch: master
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release'
    auth_token:
      secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
    artifact: /.*zip/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
