os: Visual Studio 2019
shallow_clone: true
install:
build_script:
  - 'mkdir build'
  - 'cd build'
  - 'cmake -DCMAKE_SYSTEM_VERSION=8.1 -A Win32  ..'
  - 'MSBuild.exe /p:Configuration=Release /p:PlatformToolset=v143 /p:Platform=Win32  .\win32_stratagus_dependencies.sln'
  - move build dependencies
  - 7z a dependencies.zip dependencies\
artifacts:
  - path: dependencies.zip
deploy:
  - provider: GitHub
    release: master-builds
    description: 'Automatic builds from the master branch'
    auth_token:
      secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
    artifact: /.*zip/
    draft: false
    prerelease: true
    on:
      branch: master
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release'
    auth_token:
      secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
    artifact: /.*zip/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
